import assert from "node:assert/strict";
import { createElement } from "../src/internal/lib/editor/tree";
import { applyPageLayout, unwrapPageLayout } from "../src/internal/lib/editor/page-layout";

const layout = createElement("Frame", { x: 0, y: 0, z: 0 });
layout.isLayout = true;
layout.componentRole = "master";
layout.componentId = layout.id;
const wrapper = createElement("Frame", { x: 0, y: 0, z: 0 });
wrapper.parentId = layout.id;
const slot = createElement("Frame", { x: 0, y: 0, z: 0 });
slot.parentId = wrapper.id;
slot.childrenSlot = true;
const content = createElement("Text", { x: 0, y: 0, z: 0 });
content.content = "Page-specific content";
const nested = createElement("Text", { x: 0, y: 0, z: 0 });
nested.parentId = content.id;
const parked = createElement("Frame", { x: 0, y: 0, z: 0 });
parked.parked = true;
const own = [content, nested, parked, layout, wrapper, slot];
const applied = applyPageLayout(own, own, layout.id);
assert.equal(applied.find(el => el.id === content.id)?.parentId, `layout-page-${slot.id}`);
assert.equal(applied.find(el => el.id === nested.id)?.parentId, content.id);
assert.equal(applied.find(el => el.id === parked.id)?.parentId, undefined);
assert.equal(applied.find(el => el.id === layout.id)?.parentId, undefined);
assert.deepEqual(unwrapPageLayout(applied), own);
assert.deepEqual(applyPageLayout(applied, own, layout.id), applied);
assert.deepEqual(applyPageLayout(own, [layout, wrapper], layout.id), own);
assert.deepEqual(applyPageLayout(applied, own), own);
const changed = own.map(el => el.id === wrapper.id ? { ...el, name: "Updated shared wrapper" } : el);
assert.equal(applyPageLayout(own, changed, layout.id).find(el => el.id === `layout-page-${wrapper.id}`)?.name, "Updated shared wrapper");
console.log("Page layout: nested slot, authored content, round trip, repeated application, removal, missing slot and shared updates passed.");
