import assert from 'node:assert/strict';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { normalizeTextEffects } from '../src/internal/lib/editor/text-effects';
import { TextEffectsContent } from '../src/internal/lib/render/text-effects';
import { parseElements } from '../src/internal/lib/editor/validate';
import { createElement } from '../src/internal/lib/editor/tree';

const effect = normalizeTextEffects({ hover: 'lift', scroll: 'reveal', split: 'letters', start: 90, end: 20, duration: Infinity })!;
assert.equal(effect.end, 91);
assert.equal(effect.duration, 350);
const el = { ...createElement('Text', { x: 0, y: 0, z: 0 }), textEffects: effect };
assert.deepEqual(parseElements(JSON.parse(JSON.stringify([el])))[0].textEffects, effect);
const content = 'ş 👩‍💻 e\u0301';
const html = renderToStaticMarkup(React.createElement(TextEffectsContent, { content, effects: effect }));
assert.equal((html.match(/class="pg-text-unit"/g) ?? []).length, 3);
assert.ok(html.includes('👩‍💻'));
assert.ok(html.includes('prefers-reduced-motion'));
const disabled = renderToStaticMarkup(React.createElement(TextEffectsContent, { content, effects: effect, enabled: false }));
assert.ok(disabled.includes('data-pg-text-hover="none"'));
assert.ok(disabled.includes('data-pg-text-scroll="none"'));
console.log('Text effects: persistence, ranges, graphemes and canvas disabled mode passed.');
const roll = normalizeTextEffects({ hover: 'roll', split: 'words', angle: -25, repeat: true })!;
assert.equal(roll.angle, -25);
assert.equal(normalizeTextEffects({ angle: 999 })!.angle, 60);
assert.equal(normalizeTextEffects({ repeat: 'true' })!.repeat, false);
assert.deepEqual(parseElements(JSON.parse(JSON.stringify([{ ...el, textEffects: roll }])))[0].textEffects, roll);
const rolled = renderToStaticMarkup(React.createElement(TextEffectsContent, { content: 'Merhaba dünya', effects: roll }));
assert.equal((rolled.match(/class="pg-text-roll-copy" aria-hidden="true"/g) ?? []).length, 2);
assert.ok(rolled.includes('--roll-repeat:infinite'));
assert.ok(rolled.includes('data-pg-text-hover="roll"'));
console.log('Diagonal roll: settings round-trip, bounds and hidden duplicate copies passed.');
