export const DOCS_CATALOG_TR: Record<string, { title: string; description: string; group?: string }> = {
  architecture: { title: "Sistem mimarisi", description: "Stüdyo, belgeler, sunucu ve yayımlanan sayfaların çalışma ortamı nasıl bir araya gelir?", group: "Başlangıç" },
  studio: { title: "Stüdyo iş akışı", description: "Sayfa oluşturun, katmanları düzenleyin, biçimlendirin ve kaydedilen sonucu doğrulayın.", group: "Oluşturma" },
  blocks: { title: "Yerel blok başvurusu", description: "Amaca ve düzenleme iş akışına göre gruplandırılmış tüm yerel öğe türleri.", group: "Başvuru" },
  "document-model": { title: "Belge modeli", description: "Öğe kimlikleri, üst öğe ilişkileri, stiller ve sürüm güvenliğini koruyan belge düzenleme.", group: "Başvuru" },
  "responsive-design": { title: "Duyarlı tasarım", description: "Çalışma yüzeylerini, kademeli stil geçersiz kılmalarını ve gerçek görünüm alanı kontrollerini anlayın.", group: "Oluşturma" },
  "components-layouts": { title: "Bileşenler ve düzenler", description: "Yerel bileşenleri, varyantları ve ortak sayfa düzenlerini güvenle yeniden kullanın.", group: "Oluşturma" },
  forms: { title: "Formlar ve gönderim", description: "Erişilebilir denetimler oluşturun ve bunları kendi gönderim sunucunuza bağlayın.", group: "Oluşturma" },
  interactions: { title: "Hareket ve etkileşimler", description: "Üzerine gelme durumları, tıklama eylemleri, döngülü slaytlar, kayan içerik, sekmeler ve akordeon iş akışları.", group: "Oluşturma" },
  "ai-mcp": { title: "Yapay zekâ ile üretim ve MCP", description: "Yapay zekâ ile üretimi yapılandırın, düzenleme kapsamını belirleyin ve MCP keşfini yetkilendirin.", group: "Oluşturma" },
  cli: { title: "Kodlama ajanları için CLI", description: "Terminalden yerel belgeleri inceleyin, doğrulayın, oluşturun ve güncelleyin.", group: "Başvuru" },
  revisions: { title: "Kaydetme ve revizyonlar", description: "İyimser eşzamanlılığı yönetin, taslakları kurtarın ve kaydetmeyi yayımlamadan ayırın.", group: "Başvuru" },
  "fonts-assets": { title: "Yazı tipleri, simgeler ve varlıklar", description: "Ana uygulamanın yazı tiplerini kaydedin, medya seçin ve içeriği erişilebilir tutun.", group: "Oluşturma" },
  deployment: { title: "Dağıtım ve işletim", description: "Üretim yapılandırması, güvenlik sınırları, önbellekler ve kurtarma kontrolleri.", group: "Başvuru" },
  changelog: { title: "Değişiklik günlüğü", description: "Henüz yayımlanmamış değişiklikler, dokümantasyon eklemeleri ve uyumluluk notları.", group: "Başvuru" },
  "getting-started": { title: "Başlarken", description: "Gereksinimler, kurulum ve ortam değişkenleri.", group: "Başlangıç" },
  "nextjs-setup": { title: "Next.js kurulumu", description: "Sunucuyu bağlayın, başlangıç verilerini yükleyin ve stüdyoyu açın.", group: "Başlangıç" },
  publishing: { title: "Önizleme ve yayımlama", description: "Taslakları gizli tutun, güvenle önizleyin ve yayımlanan sayfaları oluşturun.", group: "Oluşturma" },
  "data-binding": { title: "Dinamik rotalar ve veri", description: "İstek verilerini çözümleyin ve API sonuçlarını sunucuda tekrarlayın.", group: "Oluşturma" },
  templates: { title: "Şablon kayıt deposu", description: "Yeniden kullanılabilir şablon paketlerini yükleyin, doğrulayın ve bakımını yapın.", group: "Oluşturma" },
  "api-reference": { title: "API başvurusu", description: "Sunucu, istemci ve paket dışa aktarımları tek yerde.", group: "Başvuru" },
  security: { title: "Güvenlik", description: "Düzenleyici rotalarını koruyun ve güven sınırını anlayın.", group: "Başvuru" },
  troubleshooting: { title: "Sorun giderme", description: "En yaygın kurulum, CSS, veritabanı ve yapay zekâ hatalarını giderin.", group: "Başvuru" },
  agents: { title: "Kodlama ajanı rehberi", description: "Düzenlenebilir siteler oluşturan ajanlar için entegrasyon sözleşmesi.", group: "Başvuru" },
};
