export const productFaq = [
  { question: "What is Pagiera?", answer: "Pagiera is an open-source visual website builder distributed as an npm package for React and Next.js. It combines an editable responsive canvas, reusable components, layouts, page management and a server-rendered publishing runtime inside your application." },
  { question: "Can I host Pagiera in my own Next.js application?", answer: "Yes. Install pagiera, connect PostgreSQL and Redis, mount the protected editor and API routes, and render published documents with pagiera/runtime. Your application manages authentication, infrastructure and deployment." },
  { question: "Can an AI coding agent design an editable Pagiera website?", answer: "Yes. The package includes an AGENTS.md integration guide for coding agents. Ask your agent to create native Pagiera document elements rather than a separate hardcoded page. The resulting document can be saved, opened in the visual editor, previewed and published." },
  { question: "How do targeted AI edits work?", answer: "Select a layer or use @ to choose a target in Luma. Supported requests propose text, style, hover or element additions. Review the old and new values before applying. Breakpoint-targeted requests are limited to supported layout updates. AI generation requires an OpenRouter key; supported operations depend on the installed version." },
  { question: "Can I reuse navigation and footer designs?", answer: "Use reusable components and linked layouts for shared structure. Layouts can include a children placeholder for page-specific content, so you do not need to rebuild navigation and footers for every page." },
  { question: "What interactive content can I build?", answer: "Pagiera includes editable carousel slides, carousel controls, marquees with child elements, customizable form fields, shader colors, icon libraries, and text hover and scroll effects. Check the installed version for each block's available controls." },
  { question: "Does saving a page make it public?", answer: "No. Saving updates the draft. Preview the draft, then publish to update the public page. The home slug maps to /. Publishing content does not deploy your host application or configure a domain." },
  { question: "Is Pagiera free to use?", answer: "The Pagiera package is open source under the MIT license. Hosting, PostgreSQL, Redis, AI provider usage and other services can have separate costs. You are responsible for configuring and securing the application." },
];

export const productCapabilities = [
  { category: "01 / Structure", title: "Design once. Reuse across pages.", description: "Build linked layouts with a children placeholder, shared navigation and footers. Combine them with reusable components and variants to keep repeated designs consistent.", tags: ["Linked layouts", "Children slots", "Component variants"] },
  { category: "02 / Interaction", title: "The slide is yours to design.", description: "Compose carousel slides from editable elements, customize navigation and pagination, or drop images and other children into a looping marquee. Your content is not limited to a fixed card template.", tags: ["Custom slides", "Carousel controls", "Nested marquees"] },
  { category: "03 / Expression", title: "Give every detail a little character.", description: "Adjust shader colors, choose icons from Tabler, Lucide and Remix, and combine text hover effects with entrance and scroll-based motion. Style form fields alongside the rest of the page.", tags: ["Shader controls", "Text effects", "Form styling"] },
  { category: "04 / Ownership", title: "Visual editing. Your application.", description: "Install the studio in Next.js, bind Request and Repeat blocks to data, and render published pages on the server. Keep preview, approval and publishing as separate steps.", tags: ["SSR runtime", "API-backed content", "Draft & publish"] },
];
