import type { productFaq, productCapabilities } from "./product-content";

export const productFaqTr: typeof productFaq = [
  { question: "Pagiera nedir?", answer: "Pagiera, React ve Next.js için npm paketi olarak dağıtılan açık kaynaklı bir görsel web sitesi oluşturucusudur. Düzenlenebilir, duyarlı bir tuvali, yeniden kullanılabilir bileşenleri, düzenleri, sayfa yönetimini ve sunucuda işlenen bir yayınlama çalışma zamanını uygulamanızın içinde bir araya getirir." },
  { question: "Pagiera'yı kendi Next.js uygulamamda barındırabilir miyim?", answer: "Evet. pagiera paketini yükleyin, PostgreSQL ve Redis'i bağlayın, korumalı editör ve API rotalarını ekleyin ve yayımlanan belgeleri pagiera/runtime ile işleyin. Kimlik doğrulamayı, altyapıyı ve dağıtımı uygulamanız yönetir." },
  { question: "Bir yapay zekâ kodlama ajanı düzenlenebilir bir Pagiera web sitesi tasarlayabilir mi?", answer: "Evet. Paket, kodlama ajanları için bir AGENTS.md entegrasyon kılavuzu içerir. Ajanınızdan ayrı, doğrudan kodlanmış bir sayfa yerine yerel Pagiera belge öğeleri oluşturmasını isteyin. Oluşan belge kaydedilebilir, görsel editörde açılabilir, önizlenebilir ve yayımlanabilir." },
  { question: "Hedefli yapay zekâ düzenlemeleri nasıl çalışır?", answer: "Bir katman seçin veya Luma'da hedef seçmek için @ kullanın. Desteklenen istekler metin, stil, üzerine gelme ya da öğe ekleme önerileri sunar. Uygulamadan önce eski ve yeni değerleri inceleyin. Belirli bir kırılma noktasını hedefleyen istekler, desteklenen düzen güncellemeleriyle sınırlıdır. Yapay zekâ ile üretim için OpenRouter anahtarı gerekir; desteklenen işlemler yüklü sürüme bağlıdır." },
  { question: "Gezinme ve alt bilgi tasarımlarını yeniden kullanabilir miyim?", answer: "Ortak yapı için yeniden kullanılabilir bileşenler ve bağlantılı düzenler kullanın. Düzenler, sayfaya özel içerik için bir children yer tutucusu içerebilir; böylece gezinmeyi ve alt bilgileri her sayfa için yeniden oluşturmanız gerekmez." },
  { question: "Hangi etkileşimli içerikleri oluşturabilirim?", answer: "Pagiera; düzenlenebilir karusel slaytları, karusel kontrolleri, alt öğeler içeren kayan şeritler, özelleştirilebilir form alanları, shader renkleri, simge kütüphaneleri ve metin üzerine gelme ve kaydırma efektleri içerir. Her bloğun kullanılabilir kontrolleri için yüklü sürümü kontrol edin." },
  { question: "Bir sayfayı kaydetmek onu herkese açık hâle getirir mi?", answer: "Hayır. Kaydetmek taslağı günceller. Taslağı önizleyin, ardından herkese açık sayfayı güncellemek için yayımlayın. home slug'ı / yoluna karşılık gelir. İçeriği yayımlamak, ana uygulamanızı dağıtmaz veya bir alan adı yapılandırmaz." },
  { question: "Pagiera'yı kullanmak ücretsiz mi?", answer: "Pagiera paketi MIT lisansı altında açık kaynaklıdır. Barındırma, PostgreSQL, Redis, yapay zekâ sağlayıcısı kullanımı ve diğer hizmetlerin ayrı maliyetleri olabilir. Uygulamayı yapılandırmak ve güvenliğini sağlamak sizin sorumluluğunuzdadır." },
];

export const productCapabilitiesTr: typeof productCapabilities = [
  { category: "01 / Yapı", title: "Bir kez tasarlayın. Sayfalar arasında yeniden kullanın.", description: "children yer tutucusu, ortak gezinme ve alt bilgiler içeren bağlantılı düzenler oluşturun. Tekrarlanan tasarımların tutarlı kalması için bunları yeniden kullanılabilir bileşenler ve varyantlarla birleştirin.", tags: ["Bağlantılı düzenler", "Children yuvaları", "Bileşen varyantları"] },
  { category: "02 / Etkileşim", title: "Slaytı tasarlamak size kalmış.", description: "Düzenlenebilir öğelerden karusel slaytları oluşturun, gezinmeyi ve sayfalamayı özelleştirin ya da görüntüleri ve diğer alt öğeleri döngüsel bir kayan şeride yerleştirin. İçeriğiniz sabit bir kart şablonuyla sınırlı değildir.", tags: ["Özel slaytlar", "Karusel kontrolleri", "İç içe kayan şeritler"] },
  { category: "03 / İfade", title: "Her ayrıntıya biraz karakter katın.", description: "Shader renklerini ayarlayın, Tabler, Lucide ve Remix'ten simgeler seçin ve metin üzerine gelme efektlerini giriş ve kaydırmaya bağlı hareketlerle birleştirin. Form alanlarını sayfanın geri kalanıyla birlikte biçimlendirin.", tags: ["Shader kontrolleri", "Metin efektleri", "Form biçimlendirme"] },
  { category: "04 / Sahiplik", title: "Görsel düzenleme. Sizin uygulamanız.", description: "Stüdyoyu Next.js'e kurun, Request ve Repeat bloklarını verilere bağlayın ve yayımlanan sayfaları sunucuda işleyin. Önizleme, onay ve yayınlamayı ayrı adımlar olarak tutun.", tags: ["SSR çalışma zamanı", "API destekli içerik", "Taslak ve yayınlama"] },
];
